Add tests for reverse PTR records
cloudscale-ch/acceptance-tests pull request #11
Opened 2021-11-05 09:11 UTC by href

This includes a test for Floating IPs (v4/v6), and servers.

2021-12-14 11:16 UTC, gaudenz requested changes
Looks good in general. Just the change to not hardcode the list of nameservers here.

2021-12-14 11:16 UTC, gaudenz commented on test_public_network.py
> +        assert reverse_ptr(fip, 'ns3.cloudscale.ch') == f'{ptr}.'
Same as above.

2021-12-15 09:02 UTC, href commented on util.py
> +        return resolver.resolve(reverse, 'PTR').rrset[0].to_text()
I'm pretty indifferent, so I went with your suggestion.

2021-12-15 10:43 UTC, href commented on test_public_network.py
> +        assert reverse_ptr(ipv6, 'ns3.cloudscale.ch') == f'{server.name}.'
I implemented an approach that is more generic. I would have liked to surface the DNS servers we use in the test, but after trying it out I didn't feel like hiding them is a big loss.

2021-12-21 10:18 UTC, gaudenz approved these changes
LGTM now. I suggest to squash the commits before merging.

2021-12-21 12:19 UTC, merged